services:
  - type: web
    name: criterion-recommender
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 1200 --workers 1 --threads 1 --preload --max-requests 100 --max-requests-jitter 20 --worker-class sync app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PYTHONUNBUFFERED
        value: 1
      - key: TRANSFORMERS_CACHE
        value: /tmp/transformers_cache
      - key: TOKENIZERS_PARALLELISM
        value: "false"
      - key: PORT
        value: 10000
      - key: GUNICORN_CMD_ARGS
        value: "--timeout=1200 --workers=1 --threads=1 --preload --max-requests=100 --max-requests-jitter=20 --worker-class=sync"
      - key: PYTORCH_CUDA_ALLOC_CONF
        value: "max_split_size_mb:128"
      - key: CUDA_VISIBLE_DEVICES
        value: ""
    plan: free
    memory: 512MB
    buildTimeout: 1800
    healthCheckPath: / 